# Generated by Django 5.0.7 on 2024-08-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0002_rename_game_room_rename_game_player_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='room',
        ),
    ]
