# Generated by Django 5.0.7 on 2024-08-26 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0003_remove_player_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blackjack.room'),
            preserve_default=False,
        ),
    ]
