# Generated by Django 5.0.7 on 2024-08-26 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0004_player_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='outcome',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='blackjack.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('X', 'Closed')], default='O', max_length=1),
        ),
    ]
