# Generated by Django 5.0.7 on 2024-08-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0005_alter_player_outcome_alter_player_room_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackjackPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.player')),
                ('chips', models.IntegerField(default=0)),
                ('has_blackjack', models.BooleanField(default=False)),
                ('current_hand_value', models.IntegerField(default=0)),
            ],
            bases=('core.player',),
        ),
        migrations.CreateModel(
            name='BlackjackRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.room')),
                ('deck', models.JSONField(default=list)),
                ('dealer_score', models.IntegerField(default=0)),
            ],
            bases=('core.room',),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
