# Generated by Django 5.1 on 2024-08-28 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.player')),
                ('stack', models.FloatField(default=0)),
            ],
            bases=('core.player',),
        ),
        migrations.CreateModel(
            name='PokerRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.room')),
                ('deck', models.JSONField(default=list)),
            ],
            bases=('core.room',),
        ),
    ]
