# Generated by Django 5.1 on 2024-09-11 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_alter_pokerplayer_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerBroadcasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_broadcasts', to='poker.pokerroom')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
