# Generated by Django 5.1 on 2024-09-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_pokerbroadcasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerplayer',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
